### ISSUE TITLE
Sent from a t-addr and no notice given

### ISSUE THREAD

**Issue by garethtdavies** [adityapk00/zqwandroid#1]
I sent to a Sapling address and it sent from a transparent address with no warning. There were not enough funds in any Sapling addresses which is why I guess it then took from any available t-addrs but this was unexpected and I'd at least like a warning to say that I am sending from a transparent address and there are no suitable Sapling funds available.

**Comment by adityapk00** [comment]
Ah, yes. Good catch. I'll add a warning on the android app side

**Comment by adityapk00** [comment]
Maybe I should just disable sending from a tAddress

**Comment by garethtdavies** [comment]
I'd certainly be strongly in favour of that. There are plenty of existing options for using transparent addresses on mobile devices and I assume it would simplify things a little?

I can see the argument that maybe you might want to send to a taddr once in a while and it could be a bit of a hassle in that scenario  (you could still do so via the desktop app obviously) but in my opinion, the benefit of this outweighs any potential issues.

**Comment by adityapk00** [comment]
Fixed in beta3
